---
- name: Windows System Management
  hosts: windows
  gather_facts: false
  vars:
    ansible_user: Administrator
    ansible_password: "{{ windows_password }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: basic
    ansible_port: 5985

  tasks:
    - name: Ensure Windows Update service is running
      ansible.windows.win_service:
        name: wuauserv
        state: started
        start_mode: auto

    - name: Install Windows Updates
      ansible.windows.win_shell: |
        Install-Module PSWindowsUpdate -Force
        Get-WindowsUpdate -AcceptAll -Install -AutoReboot
      register: update_result

    - name: Configure Windows Defender
      ansible.windows.win_shell: |
        Set-MpPreference -DisableRealtimeMonitoring $false
        Set-MpPreference -SubmitSamplesConsent SendAllSamples

    - name: Configure Windows Time Service
      ansible.windows.win_service:
        name: w32time
        state: started
        start_mode: auto

    - name: Sync time with NTP
      ansible.windows.win_shell: |
        w32tm /config /manualpeerlist:"time.windows.com" /syncfromflags:manual
        w32tm /resync

    - name: Configure Event Log settings
      ansible.windows.win_shell: |
        wevtutil sl Application /ms:104857600
        wevtutil sl System /ms:104857600

    - name: Reboot system if required
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: update_result.changed